import Head from 'next/head'
import {BsFillMoonStarsFill, BsFillSunFill} from 'react-icons/bs'
import {useState} from 'react'
import {Inicio } from '../components/Inicio'
import {About } from '../components/About'
import {Projects } from '../components/Projects'
import {Footer } from '../components/Footer'




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mateus Masnik Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white">
        <section className=" min-h-screen" id="inicio">
          <nav className="py-10 mb-12 flex justify-between ">
          <h1 className="text-xl font-burtons">DevelopByMat</h1>
          <ul className="flex items-center">
            <li>
              {darkMode ? (
                <BsFillSunFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-xl"
                />
              ) : (
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-xl"
                />
              )}
            </li>
            <li>
              <a
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-black px-4 py-2 rounded-md ml-8 font-medium dark:text-white shadow-lg shadow-blue-500 dark:shadow-cyan-500/50 hover:animate-pulse"
                href="https://wa.me/5542988346464" 
                rel="noreferrer"
                target="_blank"
              >
                Contato
              </a>
            </li>
          </ul>
          </nav>
          <Inicio />
        </section>
        <About/>
        <Projects/>       
      </main>
      <Footer />
    </div>
  )
}
